# Generated by Django 4.0 on 2022-01-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ucet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image', models.URLField(verbose_name='Img source url')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16)),
                ('mcoms', models.PositiveSmallIntegerField()),
                ('has_skyfall', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('start_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ucet.member')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon_name', models.CharField(max_length=32, verbose_name='FontAwesome icon name')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('created', models.DateField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
                ('players', models.ManyToManyField(related_name='drafted_in', to='matches.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='matches.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoundSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('screenshot', models.URLField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration in minutes')),
                ('mcoms_destroyed', models.PositiveSmallIntegerField(default=0)),
                ('attackers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers', to='matches.team')),
                ('defenders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defenders', to='matches.team')),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.map')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_played', to='matches.player')),
                ('role', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role', to='matches.role')),
                ('round_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.roundsession')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='matches.team')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='draft1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_draft1', to='matches.teamdraft'),
        ),
        migrations.AddField(
            model_name='match',
            name='draft2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_draft2', to='matches.teamdraft'),
        ),
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.game'),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(related_name='participates_in', through='matches.Participant', to='matches.Player'),
        ),
    ]
