# Generated by Django 4.0 on 2022-01-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MatchMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.map')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='draft1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='draft2',
        ),
        migrations.AddField(
            model_name='match',
            name='leaders',
            field=models.ManyToManyField(related_name='leaders', through='matches.MatchLeader', to='matches.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='maps',
            field=models.ManyToManyField(related_name='maps', through='matches.MatchMap', to='matches.Map'),
        ),
        migrations.AddField(
            model_name='teamdraft',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='matches.match'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('player', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='playersession',
            unique_together={('player', 'round_session', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='roundsession',
            unique_together={('match', 'order')},
        ),
        migrations.AddField(
            model_name='matchmap',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchleader',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchleader',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.player'),
        ),
    ]
