# Generated by Django 4.0 on 2022-01-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_matchleader_matchmap_remove_match_draft1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMVPVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='mvp',
            field=models.ManyToManyField(related_name='mvp_votes', through='matches.MatchMVPVote', to='matches.Participant'),
        ),
        migrations.AddField(
            model_name='playersession',
            name='record_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(verbose_name='Image source URL'),
        ),
        migrations.AlterField(
            model_name='match',
            name='leaders',
            field=models.ManyToManyField(related_name='leaders', through='matches.MatchLeader', to='matches.Participant'),
        ),
        migrations.AlterField(
            model_name='matchleader',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.participant'),
        ),
        migrations.AlterField(
            model_name='roundsession',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.matchmap'),
        ),
        migrations.AddField(
            model_name='matchmvpvote',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchmvpvote',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.participant'),
        ),
    ]
