# Generated by Django 4.0 on 2022-01-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_matchmvpvote_match_mvp_playersession_record_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundsession',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.map'),
        ),
    ]
